export const SHOW_NEXT_CARD = 'SHOW_NEXT_CARD';
export const SHOW_PREVIOUS_CARD = 'SHOW_PREVIOUS_CARD';

// async
export const REQUEST_MONSTERS_PENDING = 'REQUEST_MONSTERS_PENDING';
export const REQUEST_MONSTERS_SUCCESS = 'REQUEST_MONSTERS_SUCCESS';
export const REQUEST_MONSTERS_FAILED = 'REQUEST_MONSTERS_FAILED';

export const REQUEST_MONSTER_PENDING = 'REQUEST_MONSTER_PENDING';
export const REQUEST_MONSTER_SUCCESS = 'REQUEST_MONSTER_SUCCESS';
export const REQUEST_MONSTER_FAILED = 'REQUEST_MONSTER_FAILED';